apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webrtc-frontend.fullname" . }}
  labels:
    {{- include "webrtc-frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "webrtc-frontend.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "webrtc-frontend.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          {{- if .Values.runtimeConfig.enabled }}
          volumeMounts:
            - name: app-config
              mountPath: /usr/share/nginx/html/config.json
              subPath: config.json
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if .Values.runtimeConfig.enabled }}
      volumes:
        - name: app-config
          configMap:
            name: {{ include "webrtc-frontend.fullname" . }}-config
      {{- end }}
